apiVersion: v1
kind: LimitRange
metadata:
  name: cpu-mem-limits
  namespace: demo-namespace
spec:
  limits:
  - type: Container
    max:
      cpu: "2"          # Max CPU allowed for a container
      memory: "1Gi"     # Max memory allowed for a container
    min:
      cpu: "100m"       # Min CPU required for a container
      memory: "128Mi"   # Min memory required for a container
    default:
      cpu: "500m"       # Default CPU request if not specified
      memory: "256Mi"   # Default memory request if not specified
    defaultRequest:
      cpu: "250m"       # Default CPU request
      memory: "128Mi"   # Default memory request
