apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: medical
  labels:
    run: pod
  name: pod
spec:
  containers:
  - args:
    - nginx
    image: nginx
    name: pod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
