apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  namespace: medical
  labels:
    run: pod
  name: pod2
spec:
  containers:
  - image: nginx
    name: pod
    resources: 
      requests:
        memory: "64Mi"    # Minimum memory required
        cpu: "250m"       # Minimum CPU required (0.25 CPU)
      limits:
        memory: "128Mi"   # Maximum memory allowed
        cpu: "500m"       # Maximum CPU allowed (0.5 CPU)
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
