apiVersion: v1
kind: Pod
metadata:
  name: my-app-pod-env
spec:
  containers:
    - name: my-app-container
      image: busybox
      command: ["/bin/sh", "-c", "env"]
      env:
        - name: APP_COLOR_OVERRIDE
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: APP_COLOR