apiVersion: v1
kind: Pod
metadata:
  name: my-app-files
spec:
  containers:
    - name: my-app-container
      image: busybox
      command: ["/bin/sh", "-c", "cat /etc/config/app.properties"]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: app-config-files
        items:
          - key: application.properties
            path: app.properties