apiVersion: batch/v1
kind: Job
metadata:
  name: pi-calculator
spec:
  template:
    metadata:
     name: pi-calculator
     
    spec:
      containers:
      - image: perl
        name: pi-calculator
        command: ["perl", "-Mbignum=bpi", "-wle", "print bpi(2000)"]
        resources: {}
      restartPolicy: Never
status: {}
